//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// CBTHooker_res.rc

#define IDD_MAIN                            100

#define IDS_HCBT_ACTIVATE                   100
#define IDS_HCBT_CREATEWND                  101
#define IDS_HCBT_DESTROYWND                 102
#define IDS_HCBT_MINMAX                     103
#define IDS_HCBT_SETFOCUS                   104
#define IDS_AT_NOTHING                      200
#define IDS_AT_SUSPEND                      201
#define IDS_AT_RESUME                       202
#define IDS_AT_MAXIMIZE                     203
#define IDS_AT_MINIMIZE                     204
#define IDS_AT_RESTORE                      205
#define IDS_AT_SHOW                         206
#define IDS_AT_HIDE                         207
#define IDS_AT_CLOSE                        208
#define IDS_AT_DESTROY                      209
#define IDS_STARTWATCH                      300
#define IDS_ENDWATCH                        301

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
